// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugonglmyqdfxrwqmwmeu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnb25nbG15cWRmeHJ3cW13bWV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMTQ1MzMsImV4cCI6MjA3MTc5MDUzM30.mJI5-hOqWO9edDUng2oWg5PyOsRT-G64SrLkzt4Lpa8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});